version: '3.8'

services:
  backend:
    image: tenebris2/qairline-repo:backend
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/airline_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: airline_db
