name: Fullstack CI/CD Workflow 
on:
  push:
    branches:
      - main
      - TranDuong874-cicd
  pull_request:
    branches:
      - main
      - TranDuong874-cicd

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: ${{secrets.NODE_VERSION}}
      
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      
      - name: Building Frontend
        working-directory: frontend
        run: npm run build
        
      - name: Testing Frontend
        working-directory: frontend
        # --: Tells npm to stop accepting flag, before -- is npm flag like npm install test -- other flags
        run: npm test -- --passWithNoTests --ci
      
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ secrets.PYTHON_VERSION }}
      
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
        working-directory: backend
      
      
    # integration-test:
