name: Fullstack CI/CD Workflow 
on:
  push:
    branches:
      - main
      - TranDuong874-cicd
  pull_request:
    branches:
      - main
      - TranDuong874-cicd

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v3
      
      - name: Changing to frontend directory
        run: cd frontend
        
      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ secrets.NODE_VERSION }}
      
      - name: Install dependencies
        run: npm install --verbose
      
      - name: Building Frontend
        run: npm run build
        
      - name: Testing Frontend
        run: npm run test 

      # - name: Deploying Frontend